name: Deploy GitHub Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        run: npm run deploy
